// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgj5idfT0rDwVSz3hJ-2-V64dW-bYt66A',
    appId: '1:223557697060:web:ee94d644df5962ebb1e2b1',
    messagingSenderId: '223557697060',
    projectId: 'fp-ppb-e8',
    authDomain: 'fp-ppb-e8.firebaseapp.com',
    storageBucket: 'fp-ppb-e8.appspot.com',
    measurementId: 'G-S328QBJERZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX9SZKQOVqQd51PwqjspclKz2lWKp4V2w',
    appId: '1:223557697060:android:dc3848c1e65cbc9bb1e2b1',
    messagingSenderId: '223557697060',
    projectId: 'fp-ppb-e8',
    storageBucket: 'fp-ppb-e8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgj5idfT0rDwVSz3hJ-2-V64dW-bYt66A',
    appId: '1:223557697060:web:3aedddae471a2293b1e2b1',
    messagingSenderId: '223557697060',
    projectId: 'fp-ppb-e8',
    authDomain: 'fp-ppb-e8.firebaseapp.com',
    storageBucket: 'fp-ppb-e8.appspot.com',
    measurementId: 'G-LQRKMDC26V',
  );

}