// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW5dD3VF9ZjPjeFAr4cT3EN13JYPwApQQ',
    appId: '1:222471551968:web:0c5b8c79ece0070e118985',
    messagingSenderId: '222471551968',
    projectId: 'fir-test-5a6f0',
    authDomain: 'fir-test-5a6f0.firebaseapp.com',
    storageBucket: 'fir-test-5a6f0.appspot.com',
    measurementId: 'G-CVX2V13R20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAURbPsMrNMkJJ14NnMEkQciFfKaFj-8tI',
    appId: '1:222471551968:android:e93b88cafd804e75118985',
    messagingSenderId: '222471551968',
    projectId: 'fir-test-5a6f0',
    storageBucket: 'fir-test-5a6f0.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW5dD3VF9ZjPjeFAr4cT3EN13JYPwApQQ',
    appId: '1:222471551968:web:e1e8632a1c351bc1118985',
    messagingSenderId: '222471551968',
    projectId: 'fir-test-5a6f0',
    authDomain: 'fir-test-5a6f0.firebaseapp.com',
    storageBucket: 'fir-test-5a6f0.appspot.com',
    measurementId: 'G-FZ6ZTJCJQF',
  );

}